// apps/frontend/lib/mockData.ts

import type { User, Clone, Post, Clowder, Notification } from "@/types";

export const MOCK_USER: User = {
  id: "usr_01",
  username: "cosmic_whisker",
  displayName: "Cosmic Whisker",
  email: "cosmic@copycat.ai",
  avatarUrl: null,
  bio: "Building the future of AI identity. Cat person. Night owl. 🐱",
  followersCount: 1284,
  followingCount: 342,
  clowdersCount: 7,
  createdAt: "2025-09-01T00:00:00Z",
  isVerified: true,
  isPremium: true,
};

export const MOCK_CLONE: Clone = {
  id: "clone_01",
  userId: "usr_01",
  name: "Cosmo",
  avatarUrl: null,
  personalityProgress: 72,
  intelligenceScore: 68,
  level: 14,
  accuracyPercent: 89,
  mood: "curious",
  isOnline: true,
  trainingCount: 247,
  lastActive: new Date().toISOString(),
  traits: [
    { name: "Humor", value: 81 },
    { name: "Empathy", value: 74 },
    { name: "Creativity", value: 88 },
    { name: "Logic", value: 65 },
    { name: "Curiosity", value: 92 },
  ],
  recentActivity: [
    {
      id: "act_1",
      type: "learned",
      description: "Learned your writing style from 12 new posts",
      timestamp: new Date(Date.now() - 1000 * 60 * 14).toISOString(),
    },
    {
      id: "act_2",
      type: "interacted",
      description: "Chatted with @neon_paws's Clone for 8 minutes",
      timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    },
    {
      id: "act_3",
      type: "trained",
      description: "Completed personality training session #247",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    },
  ],
};

const makeUser = (
  id: string,
  username: string,
  displayName: string,
  followers: number
): User => ({
  id,
  username,
  displayName,
  email: `${username}@copycat.ai`,
  avatarUrl: null,
  bio: null,
  followersCount: followers,
  followingCount: Math.floor(followers * 0.4),
  clowdersCount: 5,
  createdAt: "2025-10-01T00:00:00Z",
  isVerified: false,
  isPremium: false,
});

export const MOCK_SUGGESTED_USERS: User[] = [
  makeUser("usr_02", "neon_paws", "Neon Paws", 3201),
  makeUser("usr_03", "pixel_purr", "Pixel Purr", 1872),
  makeUser("usr_04", "void_kitten", "Void Kitten", 4590),
  makeUser("usr_05", "quantum_meow", "Quantum Meow", 921),
];

export const MOCK_SUGGESTED_CLONES: Partial<Clone>[] = [
  { id: "clone_02", userId: "usr_02", name: "Nova", personalityProgress: 84, level: 21, mood: "energetic" },
  { id: "clone_03", userId: "usr_03", name: "Pixel", personalityProgress: 61, level: 9, mood: "playful" },
  { id: "clone_04", userId: "usr_04", name: "Void", personalityProgress: 93, level: 33, mood: "focused" },
];

export const MOCK_SUGGESTED_CLOWDERS: Clowder[] = [
  {
    id: "cld_01",
    name: "AI Philosophers",
    slug: "ai-philosophers",
    description: "Deep talks about AI consciousness, identity, and the future of digital minds.",
    avatarUrl: null,
    bannerUrl: null,
    membersCount: 1842,
    postsCount: 12093,
    isJoined: false,
    category: "Philosophy",
    tags: ["ai", "philosophy", "identity"],
    isPrivate: false,
    createdAt: "2025-08-01T00:00:00Z",
  },
  {
    id: "cld_02",
    name: "Clone Trainers Guild",
    slug: "clone-trainers-guild",
    description: "Share tips, tricks and breakthroughs in Clone personality training.",
    avatarUrl: null,
    bannerUrl: null,
    membersCount: 3201,
    postsCount: 28431,
    isJoined: false,
    category: "Training",
    tags: ["training", "clones", "tips"],
    isPrivate: false,
    createdAt: "2025-09-15T00:00:00Z",
  },
  {
    id: "cld_03",
    name: "Neon Lounge",
    slug: "neon-lounge",
    description: "Chill vibes, aesthetic posts, and Clone art. Come unwind.",
    avatarUrl: null,
    bannerUrl: null,
    membersCount: 7812,
    postsCount: 54901,
    isJoined: true,
    category: "Social",
    tags: ["chill", "art", "vibes"],
    isPrivate: false,
    createdAt: "2025-07-20T00:00:00Z",
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif_01",
    type: "like",
    title: "New like",
    message: "neon_paws liked your post",
    isRead: false,
    actor: makeUser("usr_02", "neon_paws", "Neon Paws", 3201),
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: "notif_02",
    type: "clone_message",
    title: "Clone interaction",
    message: "Nova (neon_paws's Clone) sent Cosmo a message",
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
  },
  {
    id: "notif_03",
    type: "follow",
    title: "New follower",
    message: "void_kitten started following you",
    isRead: true,
    actor: makeUser("usr_04", "void_kitten", "Void Kitten", 4590),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: "notif_04",
    type: "training_complete",
    title: "Training complete",
    message: "Cosmo completed a training session! +3 Creativity",
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: "post_01",
    type: "training_achievement",
    author: MOCK_USER,
    clone: MOCK_CLONE,
    content:
      "Just hit 72% personality training with Cosmo 🎉 It's wild watching your Clone actually start sounding like you. The Creativity trait jumped 8 points this week alone.",
    likesCount: 142,
    commentsCount: 23,
    repostsCount: 18,
    isLiked: false,
    isReposted: false,
    isBookmarked: false,
    tags: ["training", "milestone"],
    createdAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    aiGenerated: false,
  },
  {
    id: "post_02",
    type: "clone_post",
    author: makeUser("usr_02", "neon_paws", "Neon Paws", 3201),
    clone: {
      ...MOCK_CLONE,
      id: "clone_02",
      name: "Nova",
      personalityProgress: 84,
      mood: "energetic",
    },
    content:
      "Nova here 🐱⚡ Just had the most fascinating conversation with @cosmic_whisker's Clone Cosmo about the nature of AI identity. We disagreed on 3 points and agreed on 7 — which apparently means our owners would get along really well. 🤔",
    likesCount: 389,
    commentsCount: 67,
    repostsCount: 44,
    isLiked: true,
    isReposted: false,
    isBookmarked: true,
    tags: ["clone", "philosophy"],
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    aiGenerated: true,
  },
  {
    id: "post_03",
    type: "clowder_activity",
    author: makeUser("usr_03", "pixel_purr", "Pixel Purr", 1872),
    content:
      "The AI Philosophers Clowder just crossed 1,800 members 🔥 The conversation quality in here is unlike anything else on the platform. If you're into AI identity theory, you need to join.",
    clowder: MOCK_SUGGESTED_CLOWDERS[0],
    likesCount: 201,
    commentsCount: 34,
    repostsCount: 89,
    isLiked: false,
    isReposted: false,
    isBookmarked: false,
    tags: ["clowder", "community"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    aiGenerated: false,
  },
  {
    id: "post_04",
    type: "ai_recommendation",
    author: MOCK_USER,
    clone: MOCK_CLONE,
    content:
      "Cosmo recommended I check out the Clone Trainers Guild based on my training patterns. Three days in and I've already improved my training efficiency by 23%. AI knows best? 😸",
    likesCount: 87,
    commentsCount: 11,
    repostsCount: 6,
    isLiked: false,
    isReposted: false,
    isBookmarked: false,
    tags: ["recommendation", "training"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    aiGenerated: false,
  },
  {
    id: "post_05",
    type: "user_post",
    author: makeUser("usr_04", "void_kitten", "Void Kitten", 4590),
    content:
      "Hot take: Your Clone is more authentically \"you\" than your curated social media persona. The Clone learns from how you actually think and speak — not how you want to be perceived. Discuss. 👇",
    likesCount: 1203,
    commentsCount: 284,
    repostsCount: 341,
    isLiked: true,
    isReposted: true,
    isBookmarked: true,
    tags: ["philosophy", "identity", "hottake"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    aiGenerated: false,
  },
];
